package cf_containers_broker 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Env struct {

	/*HttpsProxy - Descr: HTTPS proxy Default: <nil>
*/
	HttpsProxy interface{} `yaml:"https_proxy,omitempty"`

	/*HttpProxy - Descr: HTTP proxy Default: <nil>
*/
	HttpProxy interface{} `yaml:"http_proxy,omitempty"`

	/*NoProxy - Descr: List of comma-separated hosts to skip connecting to the proxy Default: <nil>
*/
	NoProxy interface{} `yaml:"no_proxy,omitempty"`

}