package cntlm 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type CntlmJob struct {

	/*Cntlm - Descr: Username to use for NTLM proxy Default: <nil>
*/
	Cntlm *Cntlm `yaml:"cntlm,omitempty"`

}