package docker_volume_netshare 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type DockerVolumeNetshareJob struct {

	/*Nfs - Descr: version of nfs 3 or 4 are valid options Default: 3
*/
	Nfs *Nfs `yaml:"nfs,omitempty"`

}