package docker_volume_netshare 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Nfs struct {

	/*Version - Descr: version of nfs 3 or 4 are valid options Default: 3
*/
	Version interface{} `yaml:"version,omitempty"`

	/*Options - Descr: nfs mount options Default: port=2049,nolock
*/
	Options interface{} `yaml:"options,omitempty"`

}