package swarm_manager 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Swarm struct {

	/*DiscoveryOptions - Descr: Swarm discovery options Default: []
*/
	DiscoveryOptions interface{} `yaml:"discovery_options,omitempty"`

	/*Discovery - Descr: Swarm discovery string (ie: consul://<ip>/<path>, etcd://<ip1>,<ip2>/<path>, zk://<ip1>,<ip2>/<path>, [nodes://]<ip1>,<ip2> Default: <nil>
*/
	Discovery interface{} `yaml:"discovery,omitempty"`

}