package swarm_manager 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type SwarmManagerJob struct {

	/*SwarmManager - Descr: Enable debug mode Default: false
*/
	SwarmManager *SwarmManager `yaml:"swarm_manager,omitempty"`

	/*Docker - Descr: Trust only remotes providing a certificate signed by the CA given here Default: <nil>
*/
	Docker *Docker `yaml:"docker,omitempty"`

	/*Env - Descr: HTTPS proxy that Docker should use Default: <nil>
*/
	Env *Env `yaml:"env,omitempty"`

	/*Swarm - Descr: Swarm discovery options Default: []
*/
	Swarm *Swarm `yaml:"swarm,omitempty"`

}